version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - PYTHONUNBUFFERED=1
      # Hier nutzen wir Variablen, die lokal oder auf dem Server definiert werden:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-backend,localhost,127.0.0.1}
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      # Auch hier greift die Variable:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
