# Generated by Django 5.0.6 on 2026-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Benutzer'), ('ADMIN', 'Administrator')], default='USER', max_length=10),
        ),
    ]
