# Generated by Django 5.0.6 on 2026-05-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_roughplan_timeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='goal',
        ),
        migrations.DeleteModel(
            name='RoughPlan',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
