# Generated by Django 5.0.6 on 2026-05-18 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_timeslot_unique_together_remove_timeslot_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoughPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('planned_hours', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rough_plans', to='goals.goal')),
            ],
            options={
                'unique_together': {('goal', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('planned_minutes', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='goals.goal')),
            ],
            options={
                'unique_together': {('goal', 'date')},
            },
        ),
    ]
