# Generated by Django 5.0.6 on 2026-06-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_roughplan_timeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
    ]
