# Generated by Django 5.0.6 on 2026-06-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_add_timestamps_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sessions', to='goals.timeslot'),
        ),
    ]
