# Generated by Django 5.0.6 on 2026-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_link_session_to_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Erfasst'), ('COMPLETED', 'Abgeschlossen')], default='OPEN', max_length=15),
        ),
    ]
