# Generated by Django 5.0.6 on 2026-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_add_status_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Offen'), ('COMPLETED', 'Abgeschlossen')], default='OPEN', max_length=15),
        ),
    ]
